
FYAC_Explosion = {}


FYAC_ExplosionList = {
    {	id = 0, 	name = "Grenade", 				log = true, ban = true,   protection = true, limit = 1 },
    {	id = 1, 	name = "GrenadeLauncher", 		log = true, ban = true,   protection = true, limit = 1 },
    {	id = 2, 	name = "PipeBoomb", 			log = true, ban = true,   protection = true, limit = 1 },
    {	id = 3, 	name = "PipeBoomb", 			log = true, ban = true,   protection = true, limit = 1 },
    {	id = 4, 	name = "Molotov", 				log = true, ban = true,   protection = true, limit = 1 },
    {	id = 5, 	name = "TankShell", 			log = true, ban = true,   protection = true, limit = 1 },
    {	id = 6, 	name = "Hi_Octane", 			log = true, ban = false,  protection = true, limit = 1 },
    {	id = 7, 	name = "Car", 					log = true, ban = false,  protection = true, limit = 1 },
    {	id = 8, 	name = "Plance", 				log = true, ban = false,  protection = true, limit = 1 },
    {	id = 9, 	name = "PetrolPump", 			log = true, ban = false,  protection = true, limit = 10 },
    {	id = 10, 	name = "Bike", 					log = true, ban = false,  protection = true, limit = 1 },
    {	id = 11, 	name = "Dir_Steam", 			log = true, ban = false,  protection = true, limit = 1 },
    {	id = 12, 	name = "Dir_Flame", 			log = true, ban = false,  protection = true, limit = 2 },
    {	id = 13, 	name = "Dir_Water_Hydrant", 	log = true, ban = false , protection = true, limit = 6 },
    {	id = 14, 	name = "Dir_Gas_Canister", 		log = true, ban = false,  protection = true, limit = 6 },
    {	id = 15, 	name = "Boat", 					log = true, ban = false,  protection = true, limit = 1 },
    {	id = 16, 	name = "Ship_Destroy", 			log = true, ban = false,  protection = true, limit = 1 },
    {	id = 17, 	name = "Truck", 				log = true, ban = false,  protection = true, limit = 1 },
    {	id = 18, 	name = "Bullet", 				log = true, ban = false,  protection = true, limit = 1 },
    {	id = 19, 	name = "SmokeGrenadeLauncher",	log = true, ban = true,   protection = true, limit = 1 },
    {	id = 20, 	name = "SmokeGrenade", 			log = true, ban = true,   protection = true, limit = 1 },
    {	id = 21, 	name = "BZGAS", 				log = true, ban = true,   protection = true, limit = 1 },
    {	id = 22, 	name = "Flare", 				log = true, ban = true,   protection = true, limit = 1 },
    {	id = 23, 	name = "Gas_Canister", 			log = true, ban = false,  protection = true, limit = 1 },
    {	id = 24, 	name = "Extinguisher",			log = true, ban = false,  protection = true, limit = 1 },
    {	id = 25, 	name = "Programmablear", 		log = true, ban = false,  protection = true, limit = 1 },
    {	id = 26, 	name = "Train", 				log = true, ban = false,  protection = true, limit = 1 },
    {	id = 27, 	name = "Barrel", 				log = true, ban = false,  protection = true, limit = 1 },
    {	id = 28, 	name = "PROPANE", 				log = true, ban = false,  protection = true, limit = 1 },
    {	id = 29, 	name = "Blimp", 				log = true, ban = false,  protection = true, limit = 2 },
    {	id = 30, 	name = "Dir_Flame_Explode", 	log = true, ban = false,  protection = true, limit = 1 },
    {	id = 31, 	name = "Tanker", 				log = true, ban = false,  protection = true, limit = 2 },
    {	id = 32, 	name = "PlaneRocket", 			log = true, ban = false,  protection = true, limit = 1 },
    {	id = 33, 	name = "Gas_Tank", 				log = true, ban = false,  protection = true, limit = 1 },
    {	id = 34, 	name = "VehicleBullet", 		log = true, ban = true,   protection = true, limit = 1 },
    {	id = 35, 	name = "FireWork", 				log = true, ban = true,   protection = true, limit = 1 },
    {	id = 36, 	name = "SnowBall", 				log = true, ban = false,  protection = true, limit = 1 },
    {	id = 37, 	name = "ProxMine", 				log = true, ban = true,   protection = true, limit = 1 },
    {	id = 38, 	name = "Valkyrie_Cannon", 		log = true, ban = true,   protection = true, limit = 1 },

}