FYAC_B = {}

FYAC_B.Events = {
  "mellotrainer:adminKick",
  'antilynx8:anticheat',
  'antilynxr4:detect',
  'antilynxr6:detection',
  "HCheat:TempDisableDetection",
  'ynx8:anticheat',
  'antilynx8r4a:anticheat',
  'lynx8:anticheat',
  'AntiLynxR4:kick',
  'esx_spectate:kick',
  'AntiLynxR4:log',
  'chat:server:ServerPSA',
  'd0pamine_xyz:getFuckedNigger',
  'adminmenu:allowall',
  'esx_mafiajob:confiscatePlayerItem',
  'esx_jailer:sendToJail',
  'NB:recruterplayer',
  ':tunnel_req',
  'f0ba1292-b68d-4d95-8823-6230cdf282b6',
  'gambling:spend',
  'hentailover:xdlol',
  'OG_cuffs:cuffCheckNearest',
  'display',
  'advancedFuel:setEssence',
  'esx:jackingcar',
  "lester:vendita",
  "xex_streetfight:pay",
  "rpv_uber:success",
  "devtoolOpening",
}